export interface TocItem {
    id: string;
    title: string;
    level: number;
}

export const tocItems: TocItem[] = [
    { id: "dan-nhap", title: "Dẫn Nhập", level: 2 },
    { id: "nen-tang-phan-dinh", title: "Nền Tảng Phân Định Thần Khí", level: 2 },
    { id: "nguon-goc-lich-su", title: "Nguồn Gốc Lịch Sử", level: 3 },
    { id: "bien-chung", title: "An Ủi & Sầu Khổ Thiêng Liêng", level: 3 },
    { id: "nam-chia-khoa", title: "Năm Chìa Khóa Phân Định", level: 3 },
    { id: "tien-trinh-thang-tien", title: "Tiến Trình Thăng Tiến Tâm Linh", level: 2 },
    { id: "lau-dai-noi-tam", title: "Lâu Đài Nội Tâm", level: 3 },
    { id: "dem-toi-linh-hon", title: "Đêm Tối Linh Hồn", level: 3 },
    { id: "ranh-gioi-tam-ly", title: "Ranh Giới Tâm Lý", level: 2 },
    { id: "phong-chieu-cai-toi", title: "Phóng Chiếu Cái Tôi", level: 3 },
    { id: "phan-dinh-lam-sang", title: "Phân Định Lâm Sàng", level: 3 },
    { id: "dau-chi-khach-quan", title: "Dấu Chỉ Khách Quan", level: 2 },
    { id: "lectio-divina", title: "Lectio Divina", level: 3 },
    { id: "hoa-trai-thanh-than", title: "Hoa Trái Thánh Thần", level: 3 },
    { id: "bac-ai", title: "Chiều Kích Bác Ái", level: 3 },
    { id: "khung-phap-ly", title: "Khung Pháp Lý Giáo Hội", level: 2 },
    { id: "tong-ket", title: "Tổng Kết Luận", level: 2 },
    { id: "nguon-trich-dan", title: "Nguồn Trích Dẫn", level: 2 },
];

export interface Reference {
    id: number;
    text: string;
    url: string;
}

export const references: Reference[] = [
    { id: 1, text: "ĐỨC GIÊ-SU KI-TÔ - ĐƯỜNG NHẬN BIẾT THIÊN CHÚA", url: "https://hdgmvietnam.com/chi-tiet/duc-gie-su-ki-to---duong-nhan-biet-thien-chua" },
    { id: 2, text: "Giáo Lý Thánh Kinh: Bài 3: Thiên Chúa là Cha toàn năng", url: "https://tgpsaigon.net/bai-viet/giao-ly-thanh-kinh-bai-3-%E2%80%93-thien-chua-la-cha-toan-nang-60387" },
    { id: 3, text: "Nhận Biết Thiên Chúa | Scribd", url: "https://www.scribd.com/document/858370979/4" },
    { id: 4, text: "Thiên Chúa của chúng ta, là Chúa Duy Nhất", url: "https://vntaiwan.catholic.org.tw/caotinh/dchuacha.htm" },
    { id: 5, text: "KINH NGHIỆM THIÊNG LIÊNG", url: "https://hdgmvietnam.com/chi-tiet/kinh-nghiem-thieng-lieng-54351" },
    { id: 6, text: "Chú giải các quy tắc nhận định thần loại của Thánh I-Nhã", url: "https://linhthao.net/wp-content/uploads/2014/03/NDTL-Toner.pdf" },
    { id: 7, text: "Tôn giáo: thiêng hay tục", url: "https://vjol.info.vn/index.php/rsr/article/download/23845/20385" },
    { id: 8, text: "Thần học Versus Tôn giáo học", url: "https://www.hvanphongso.edu.vn/2023/04/than-hoc-versus-ton-giao-hoc.html" },
    { id: 9, text: "Kinh nghiệm về Thiên Chúa hay chỉ là gặp gỡ chính mình?", url: "https://tgpsaigon.net/bai-viet/kinh-nghiem-ve-thien-chua-hay-chi-la-gap-go-chinh-minh-70773" },
    { id: 10, text: "Năm chìa khóa để phân định theo Thánh I-Nhã", url: "https://phanxico.vn/2017/08/18/nam-chia-khoa-de-phan-dinh-theo-thanh-i-nha/" },
    { id: 11, text: "Đọc Hồi Ký Thánh I-Nhã, vị thánh ruột của tôi", url: "https://dongten.net/doc-hoi-ky-thanh-i-nha-vi-thanh-ruot-cua-toi/" },
    { id: 12, text: "BÀI GIÁO LÝ VỀ SỰ PHÂN ĐỊNH, BÀI 9. SỰ AN ỦI", url: "https://xuanbichvietnam.net/trangchu/bai-giao-ly-ve-su-phan-dinh-bai-9-su-an-ui/" },
    { id: 13, text: "Quy tắc phân định thần loại", url: "https://linhthao.net/luutru/133" },
    { id: 14, text: "Sầu khổ thiêng liêng", url: "https://dongten.net/liempham/caunguyen13.htm" },
    { id: 15, text: "Đức cha Lambert de la Motte và việc phân định thần loại", url: "https://tgpsaigon.net/bai-viet/duc-cha-lambert-de-la-motte-va-viec-phan-dinh-than-loai-67096" },
    { id: 16, text: "Quy Tắc Phân Định Và Một Vài Hướng Dẫn Thực Hành", url: "https://dongten.net/quy-tac-phan-dinh-va-mot-vai-huong-dan-thuc-hanh/" },
    { id: 17, text: "Làm sao để nhận ra Chúa?", url: "https://gphaiphong.org/chi-tiet/lam-sao-de-nhan-ra-chua" },
    { id: 18, text: "Suy niệm, chiêm niệm và Linh Thao của Thánh I-Nhã Loyola", url: "https://tranngochuynh.wordpress.com/2025/11/13/suy-niem-chiem-niem-va-linh-thao-cua-thanh-i-nha-loyola-nhu-mot-truong-hoc-chiem-niem/" },
    { id: 19, text: "Bài Giáo Lý của ĐTC Phanxicô về Ơn kính sợ Thiên Chúa", url: "https://www.giaophanbaria.org/thanh-kinh-giao-ly/giao-ly/2014/07/28/bai-giao-ly-cua-dtc-phanxico-ve-on-kinh-so-thien-chua.html" },
    { id: 20, text: "5 NỀN TẢNG ĐỂ PHÂN ĐỊNH TRÊN LỘ TRÌNH DẪN ĐẾN SỰ BÌNH AN", url: "https://hdgmvietnam.com/chi-tiet/5-nen-tang-de-phan-dinh-tren-lo-trinh-dan-den-su-binh-an-cua-thien-chua-50279" },
    { id: 21, text: "Thánh Têrêsa Chúa Giêsu và Lâu Đài Nội Tâm", url: "https://gpcantho.com/wp-content/uploads/2022/10/eBookLauDaiNoiTam.pdf" },
    { id: 22, text: "Ngày 15/10: Thánh Tê-rê-sa A-vi-la, Trinh nữ, Tiến sĩ Hội Thánh", url: "https://giaophanhatinh.org/ngay-15-10-thanh-te-re-sa-a-vi-la-trinh-nu-tien-si-hoi-thanh-1515-1582.htdiocese" },
    { id: 23, text: "BẢY GIAI ĐOẠN CỦA LÂU ĐÀI NỘI TÂM CỦA THÁNH TÊRÊXA", url: "https://hdgmvietnam.com/chi-tiet/bay-giai-doan-cua-lau-dai-noi-tam-cua-thanh-terexa-avila-qua-hinh-anh-43998" },
    { id: 24, text: "Chương XIII. Tâm nguyện", url: "https://augustino.net/nhan-biet-tinh-yeu-doi-voi-thien-chua-chuong-13" },
    { id: 25, text: "CẦU NGUYỆN THEO THÁNH TÊRÊSA AVILA", url: "https://mtgphanthiet.org/cau-nguyen-theo-thanh-teresa-avila/" },
    { id: 26, text: "Cầu nguyện chiêm niệm là gì?", url: "https://www.tonggiaophanhanoi.org/cau-nguyen-chiem-niem-la-gi-cung-nhau-hoc-giao-ly/" },
    { id: 27, text: "Tâm tình giữa những người bạn: Cầu nguyện với thánh Têrêsa Avila", url: "https://daminhtamhiep.net/2021/11/tam-tinh-giua-nhung-nguoi-ban-cau-nguyen-voi-thanh-teresa-avila/" },
    { id: 28, text: "Đời thánh hiến dưới mắt thánh Têrêxa Avila", url: "https://dcctvn.org/doi-thanh-hien-duoi-mat-thanh-terexa-avila/" },
    { id: 29, text: "THANH LUYỆN THIÊNG LIÊNG MÙA CHAY THEO THÁNH GIOAN", url: "https://svcghanoi.com/thanh-luyen-thieng-lieng-mua-chay-theo-thanh-gioan-thanh-gia.html" },
    { id: 30, text: "ĐÊM TỐI TÂM HỒN", url: "https://hoanthiensaubay.wordpress.com/2025/03/11/dem-toi-tam-hon/" },
    { id: 31, text: "CHA WILFRID STINISSEN GIẢI THÍCH VỀ ĐÊM TỐI THIÊNG LIÊNG", url: "https://hdgmvietnam.com/chi-tiet/cha-wilfrid-stinissen-giai-thich-ve-dem-toi-thieng-lieng-54337" },
    { id: 32, text: "Đêm tối linh hồn - Giáo Phận Ban Mê Thuột", url: "https://gpbanmethuot.net/van-hoc-nghe-thuat/dem-toi-linh-hon-11221.html" },
    { id: 33, text: "Gioan Thánh Giá, Tình Yêu và Hy Sinh", url: "https://dongcatminh.org/gioan-thanh-gia-tinh-yeu-va-hy-sinh/" },
    { id: 34, text: "Gioan Thánh Giá và bài Thánh thi Tình yêu", url: "https://tgpsaigon.net/bai-viet/gioan-thanh-gia-va-bai-thanh-thi-tinh-yeu-38073" },
    { id: 35, text: "Trưởng Thành Thiêng Liêng với Trưởng Thành Cảm Tính", url: "https://vntaiwan.catholic.org.tw/syquy/2chuong.htm" },
    { id: 36, text: "Phân định thiêng liêng", url: "https://geocities.ws/liempham/dhtl.htm" },
    { id: 37, text: "Đêm tối linh hồn - lebaotinhbmt.com", url: "https://lebaotinhbmt.net/quan-van/dem-toi-linh-hon-4193.html" },
    { id: 38, text: "LỜI CẦU NGUYỆN GIÚP VƯỢT QUA CHÁN NẢN VÀ TRẦM CẢM", url: "https://hdgmvietnam.com/chi-tiet/loi-cau-nguyen-giup-vuot-qua-chan-nan-va-tram-cam-37896" },
    { id: 39, text: "7 dấu hiệu bạn đang trải qua thời kỳ Đêm Tối của Linh Hồn", url: "https://gaiaheartliving.vn/7-dau-hieu-ban-dang-trai-qua-thoi-ky-den-toi-cua-linh-hon/" },
    { id: 40, text: "Kinh nghiệm thiêng liêng", url: "https://tgpsaigon.net/bai-viet/kinh-nghiem-thieng-lieng-72269" },
    { id: 41, text: "Thực Hành Lectio Divina", url: "https://nutychuagiesulinhmuc.com/thuc-hanh-lectio-divina/" },
    { id: 42, text: "Chia Sẻ Về Cách Suy Niệm Trong Phương Pháp Lectio Divina", url: "https://dongten.net/chia-se-ve-cach-suy-niem-trong-phuong-phap-lectio-divina/" },
    { id: 43, text: "Lectio Divine (Đọc Và Suy Niệm Lời Chúa)", url: "https://daminhvn.net/duc-tin-van-hoa/van-hoa-xa-hoi/lectio-divine-doc-va-suy-niem-loi-chua-8081.html" },
    { id: 44, text: "Phương pháp cầu nguyện: Lectio Divina", url: "https://www.tonggiaophanhanoi.org/phuong-phap-cau-nguyen-lectio-divina/" },
    { id: 45, text: "ĐỌC KINH THÁNH THEO PHƯƠNG PHÁP LECTIO DIVINA", url: "https://hdgmvietnam.com/chi-tiet/doc-kinh-thanh-theo-phuong-phap-lectio-divina-48910" },
    { id: 46, text: "BÀI 15. NHỮNG HOA TRÁI CỦA CHÚA THÁNH THẦN", url: "https://xuanbichvietnam.net/trangchu/bai-giao-ly-ve-chua-thanh-than-va-hien-the-bai-15-nhung-hoa-trai-cua-chua-thanh-than-niem-vui/" },
    { id: 47, text: "12 Hoa Quả Chúa Thánh Thần", url: "https://www.conggiao.org/12-hoa-qua-chua-thanh-than/" },
    { id: 48, text: "Các hoa trái của Chúa Thánh Thần", url: "https://liengiaophan.de/tam-linh/1559-c%C3%A1c-hoa-tr%C3%A1i-c%E1%BB%A7a-ch%C3%BAa-th%C3%A1nh-th%E1%BA%A7n.html" },
    { id: 49, text: "ĐẶC SỦNG VÀ HOA TRÁI CỦA CHÚA THÁNH THẦN", url: "https://khoi-nguon.com/index.php?option=com_content&view=article&id=1480" },
    { id: 50, text: "Hoa trái thiêng liêng của một đời sống thánh khiết", url: "https://tonggiaophanhue.org/loi-chua/suy-niem-moi-ngay/hoa-trai-thieng-lieng-cua-mot-doi-song-thanh-khiet/" },
    { id: 51, text: "Ở lại trong Chúa là điều kiện để sinh nhiều hoa trái", url: "https://www.tonggiaophanhanoi.org/o-lai-trong-chua-la-dieu-kien-de-sinh-nhieu-hoa-trai/" },
    { id: 52, text: "Bí Tích Thánh Thể Trong Đời Sống Thánh Hiến", url: "https://giaophanlangson.net/noi-dung/bi-tich-thanh-the-trong-doi-song-thanh-hien-7298-08592606102018" },
    { id: 53, text: "Mầu Nhiệm Thánh Thể Trong Đời Sống Hội Thánh", url: "https://gpcantho.com/mau-nhiem-thanh-the-trong-doi-song-hoi-thanh/" },
    { id: 54, text: "THÔNG ĐIỆP CARITAS IN VERITATE - BÁC ÁI TRONG CHÂN LÝ", url: "http://caritasvietnam.org/datafiles/files/BacAiTrongChanLy.pdf" },
    { id: 55, text: "THÔNG ĐIỆP DEUS CARITAS EST CỦA ĐỨC THÁNH CHA", url: "https://www.vatican.va/content/benedict-xvi/vi/encyclicals/documents/hf_ben-xvi_enc_20051225_deus-caritas-est.html" },
    { id: 56, text: "THÔNG ĐIỆP DEUS CARITAS EST - THIÊN CHÚA LÀ TÌNH YÊU (HĐGM)", url: "https://hdgmvietnam.com/chi-tiet/thong-diep-deus-caritas-est-thien-chua-la-tinh-yeu--49105" },
    { id: 57, text: "Bài thuyết trình: Bác ái xã hội, Nghề hay Sứ mạng", url: "https://www.tonggiaophanhanoi.org/bai-thuyet-trinh-bac-ai-xa-hoi-nghe-hay-su-mang-lm-giuse-nguyen-van-diem/" },
    { id: 58, text: "Mẹ Têrêsa Calcutta và Thánh Thể", url: "http://www.giaoxukesat.com/me-teresa-calcutta-va-thanh-the/" },
    { id: 59, text: "Phụng Vụ LỄ MẸ TÊRÊSA CALCUTTA - 05/09", url: "http://mcchrist.org/phung-vu/phung-vu-le-me-teresa-calcutta-05-09-194.html" },
    { id: 60, text: "Ngày 05/09: Thánh Têrêsa Calcutta, nữ tu", url: "https://tgpsaigon.net/bai-viet/ngay-05-09-thanh-teresa-calcuttanu-tu-47938" },
    { id: 61, text: "Linh Đạo Mẹ Têrêsa Calcutta", url: "https://nguoitinhuu.org/sachtruyen/Teresa/tinhyeu2.html" },
    { id: 62, text: "Bí Quyết Sống của Mẹ Têrêsa thành Calcutta", url: "http://www.liengiaophan.de/images/pdf/2_Bi%CC%81_Quye%CC%82%CC%81t_So%CC%82%CC%81ng_cu%CC%89a_Me_Teresa_Cancutta.pdf" },
    { id: 63, text: "MẸ TÊRÊSA CALCUTTA: GẶP CHÚA NƠI NGƯỜI NGHÈO", url: "https://hdgmvietnam.com/chi-tiet/me-teresa-calcutta-nguoi-gap-chua-noi-nguoi-ngheo-va-nguoi-dau-kho-34249" },
    { id: 64, text: "Nguyên văn văn kiện mới của Bộ Giáo Lý Đức Tin: Các Quy Định...", url: "https://vietcatholic.net/News/Home/Article/290036" },
    { id: 65, text: "Mặc khải công khai và mặc khải tư trong đời sống Hội Thánh", url: "https://cgvdt.vn/mac-khai-cong-khai-va-mac-khai-tu-trong-doi-song-hoi-thanh_a22466" },
];
